### ISSUE TITLE
为什么取消整页剪藏呢

### ISSUE THREAD

**Issue by addstone** [xudafeng/yuque-chrome-extension#100]
1.希望添加上这个功能。
2.常用的Clip to OneNote里面的整页/区域/文章 很好用，能否加上呢。
3.快捷键波浪号唤起与ESC取消很好用，能否也加上呢。
4.希望能剪藏到默认的地方，稍后再去语雀整理归类。

**Comment by addstone** [comment]
5.语雀可以设置开关[来自剪藏] 这个标识吗。我会用一个单独的知识库来存放浏览器剪藏的内容

**Comment by xudafeng** [comment]
为什么没有提供全文剪藏的说明：
https://www.yuque.com/yuque/yuque-browser-extension/faq

**Comment by xudafeng** [comment]
@addstone 建议收到，非常感谢提供。

后面有具体问题或者建议可以新开issue或者到语雀文档评论。
