### ISSUE TITLE
选中父元素自动取消子元素选中

### ISSUE THREAD

**Issue by kinfuy** [xudafeng/yuque-chrome-extension#104]
当前选中父子元素会输出两次🤔

**Comment by moshangqi** [comment]
是在误触点情况线同时选中的父子元素吗？
选中父元素自动取消子元素的选中可能会有点问题，比如先选中父元素，然后去点击子元素会出现选中不了的情况。如果按照操纵时序去取消父元素可能也会有点困惑。

**Comment by kinfuy** [comment]
我感觉选择更大范围，自动去除包含范围符合直觉，再次点击取消选中即可，我简单的实现了一下，可以试试看🤔

**Comment by moshangqi** [comment]
了解了你的想法了，这块我们试试，晚些时候给回复。

**Comment by moshangqi** [comment]
这块能力我们下个版本会加上你提的这个优化，不过到时候我们的选取方案会重构。这块我就先把问题和 pr 都关掉啦😊。
