### ISSUE TITLE
退出选取是否能够更明显一些，独立入口不与关闭整个工具'x' 关联

### ISSUE THREAD

**Issue by kinfuy** [xudafeng/yuque-chrome-extension#106]

**Comment by moshangqi** [comment]
这个是什么意思喃？有点没太明白

**Comment by kinfuy** [comment]
一开始没有使用明白，不知道哪里可以退出当前选取状态😄，不知道是不是只有我有这个疑惑

**Comment by moshangqi** [comment]
是指在选取的时候不知道咋退出吗？比如这样吗
![image](https://github.com/yuque/yuque-chrome-extension/assets/50158871/c44156cf-0545-4775-8189-ebc0550d93c1)
还是不知道剪藏完成不知道咋退出，是那个关闭按钮太隐晦了吗？
