### ISSUE TITLE
将来会考虑支持Firefox吗？

### ISSUE THREAD

**Issue by Shapooo** [xudafeng/yuque-chrome-extension#176]
会考虑增加Firefox插件吗？

**Comment by xudafeng** [comment]
@Shapooo 语雀的 Firefox 和 Safari 用户太少了，短期不会考虑支持这两款浏览器。

推荐使用 Chrome 或 Edge

**Comment by xudafeng** [comment]
https://www.yuque.com/yuque/yuque-browser-extension/faq
