### ISSUE TITLE
服务器是不是崩了

### ISSUE THREAD

**Issue by xiaochaomi** [xudafeng/yuque-chrome-extension#181]

**Comment by TullyMonster** [comment]
好像也是，我的也是。会自动重定向到`https://yuque.com/500?real_status=500`

**Comment by chenxingyuu** [comment]
崩了

**Comment by cooljser** [comment]
+1

**Comment by F1ncyJ** [comment]
<img width="1419" alt="image" src="https://github.com/yuque/yuque-chrome-extension/assets/28106693/76b88264-e7f7-4745-970b-0a8a13bf5b8a">
<img width="1307" alt="image" src="https://github.com/yuque/yuque-chrome-extension/assets/28106693/2afa4712-6ef4-4f80-bc30-c266bfb7c429">
🥶

**Comment by moshangqi** [comment]
语雀依赖的数据库服务出现大面积网络故障。语雀受其影响，出现无法访问的情况（只影响服务，不影响用户在语雀存储的数据，不会引起数据丢失），正在紧急恢复中。

**Comment by xudafeng** [comment]
非常抱歉，语雀出现大面积网络故障，出现无法访问的情况，此故障，不会影响用户在语雀存储的数据，不会引起数据丢失，我们正在紧急恢复中，再次抱歉给你带来的损失。

**Comment by Nes200** [comment]
没有渠道发布服务器崩了的信息

**Comment by xudafeng** [comment]
https://weibo.com/6448460373/NpboWiRYJ?pagetype=profilefeed

**Comment by Blanket58** [comment]
完了哈，这波故障有人要3.25了

**Comment by sisyphus1212** [comment]
> 非常抱歉，语雀出现大面积网络故障，出现无法访问的情况，此故障，不会影响用户在语雀存储的数据，不会引起数据丢失，我们正在紧急恢复中，再次抱歉给你带来的损失。



> 非常抱歉，语雀出现大面积网络故障，出现无法访问的情况，此故障，不会影响用户在语雀存储的数据，不会引起数据丢失，我们正在紧急恢复中，再次抱歉给你带来的损失。

你们在干鸡儿呢？还没修好？

**Comment by yuankai2calm** [comment]
想请问是经常崩吗， 我上周五开始用，今天下午就突然崩了。

**Comment by yuankai2calm** [comment]
> 完了哈，这波故障有人要3.25了

3.25是啥意思

**Comment by cooljser** [comment]
> 想请问是经常崩吗， 我上周五开始用，今天下午就突然崩了。

用了一年多，第一次碰到

**Comment by yuankai2calm** [comment]
> > 非常抱歉，语雀出现大面积网络故障，出现无法访问的情况，此故障，不会影响用户在语雀存储的数据，不会引起数据丢失，我们正在紧急恢复中，再次抱歉给你带来的损失。
> 
> > 非常抱歉，语雀出现大面积网络故障，出现无法访问的情况，此故障，不会影响用户在语雀存储的数据，不会引起数据丢失，我们正在紧急恢复中，再次抱歉给你带来的损失。
> 
> 你们在干鸡儿呢？还没修好？

讲真是慢， 好歹先把备用服务搞起来， 再慢慢去改bug.修复问题。  我来回不停的在看起来没

**Comment by yuankai2calm** [comment]
> > 想请问是经常崩吗， 我上周五开始用，今天下午就突然崩了。
> 
> 用了一年多，第一次碰到

OK, 那就好，thanks bro.

**Comment by forMyReason** [comment]
我看去年知乎上就有说雨雀准备开源，啥时候开源啊？那是不是有本地部署的可能性。今天崩一次，我突然意识到文件不在本地的这个问题，确实很耽误事儿。

**Comment by Dragon-yy** [comment]
建议整个打包导出功能，或者定期同步到本地的功能

**Comment by awefeng** [comment]
能不能先把服务起来，数据覆盖了就覆盖了啊，宕机5个小时找数据？关键5个小时还找不到！你们是人不？一沓明天要用的文档在上面。恢复时间也没有，反馈渠道也没有！

**Comment by moshangqi** [comment]
> 能不能先把服务起来，数据覆盖了就覆盖了啊，宕机5个小时找数据？关键5个小时还找不到！你们是人不？一沓明天要用的文档在上面。恢复时间也没有，反馈渠道也没有！

我们正在紧急恢复中，再次抱歉给你带来的损失。修复后我们会第一时间通知，麻烦再稍等下 🙇

**Comment by la3rence** [comment]
我还是刷了新闻才知道这事。😅
话说语雀有和用户签 SLA 吗？

**Comment by xiaochaomi** [comment]
应该快好了，现在可以进去

**Comment by moshangqi** [comment]
各位亲爱的语雀用户：
语雀的服务现已全部恢复正常，用户访问各端语雀可正常使用。
今日故障严重干扰了所有语雀用户的使用，对此我们深感抱歉。
后续我们将发布正式公告同步情况。

**Comment by sisyphus1212** [comment]
垃圾产品，毁我青春，让你们的产品经理吃屎去，妈的越用越卡，4年的东西转都转不出来

**Comment by sisyphus1212** [comment]
vscode + 插件（git + Typora + Excel Viewer + Excalidraw + Markdown Preview Enhanced + Marp + vscode-reveal）yyds
