### ISSUE TITLE
0.5.0版本无法使用

### ISSUE THREAD

**Issue by Zephyr-Zhang99** [xudafeng/yuque-chrome-extension#200]
<img width="671" alt="image" src="https://github.com/yuque/yuque-chrome-extension/assets/86707522/a6843082-7303-4500-a114-69acccfa73a1">

**Comment by moshangqi** [comment]
这是在啥操作时候出现的报错喃？

**Comment by Zephyr-Zhang99** [comment]
> 这是在啥操作时候出现的报错喃？
没有任何操作，页面渲染后控制台就有。点击插件图标没有任何反应，窗口打不开

**Comment by moshangqi** [comment]
> > 这是在啥操作时候出现的报错喃？
> > 没有任何操作，页面渲染后控制台就有。点击插件图标没有任何反应，窗口打不开

我这边暂未复现你的 case ，请问你那边是任意页面都稳定复现吗？还是只是某些页面无法打开？

**Comment by Zephyr-Zhang99** [comment]
> > > 这是在啥操作时候出现的报错喃？
> > > 没有任何操作，页面渲染后控制台就有。点击插件图标没有任何反应，窗口打不开
> 
> 我这边暂未复现你的 case ，请问你那边是任意页面都稳定复现吗？还是只是某些页面无法打开？
重新安装扩展后可以了
