### ISSUE TITLE
edge 启用语雀插件时，打开 12306 页面会导致浏览器卡死

### ISSUE THREAD

**Issue by code-artisan-zx** [xudafeng/yuque-chrome-extension#215]
插件版本：0.5.2
edge 版本：119.0.2151.97 (正式版本) (64 位)
edge 浏览器启用语雀插件时，打开 12306 网站会出现 CPU 跟内存异常升高的问题，导致整个浏览器卡死无法使用
![QQ截图20231130211558](https://github.com/yuque/yuque-chrome-extension/assets/26058690/231df695-322b-45de-833e-f2a6535da317)
![QQ截图20231130211631](https://github.com/yuque/yuque-chrome-extension/assets/26058690/c57939b7-0ec1-4ef1-ad4f-e105119fe1e3)

**Comment by moshangqi** [comment]
> 插件版本：0.5.2 edge 版本：119.0.2151.97 (正式版本) (64 位) edge 浏览器启用语雀插件时，打开 12306 网站会出现 CPU 跟内存异常升高的问题，导致整个浏览器卡死无法使用 ![QQ截图20231130211558](https://private-user-images.githubusercontent.com/26058690/286942589-231df695-322b-45de-833e-f2a6535da317.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTMwMDYsIm5iZiI6MTcwMTM1MjcwNiwicGF0aCI6Ii8yNjA1ODY5MC8yODY5NDI1ODktMjMxZGY2OTUtMzIyYi00NWRlLTgzM2UtZjJhNjUzNWRhMzE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDEzNTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzOWIwOGMxZjEzNWQ4ZTdjMzI1MGRkZGE2MDc5ZGI3Y2EzMTkzMjFkZGQ3Yzk5N2NmNGJkOTlmOTIxMDA2ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WhYHyrowy9A_G6Xmv_-N7EBCR1VHit1xMGfRiH7lAGc) ![QQ截图20231130211631](https://private-user-images.githubusercontent.com/26058690/286942637-c57939b7-0ec1-4ef1-ad4f-e105119fe1e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNTMwMDYsIm5iZiI6MTcwMTM1MjcwNiwicGF0aCI6Ii8yNjA1ODY5MC8yODY5NDI2MzctYzU3OTM5YjctMGVjMS00ZWYxLWFkNGYtZTEwNTExOWZlMWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDEzNTgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjMjJlZDRmMzdkZTJjMDJkZjY0MzcxYTZiYjdhZTI1YmNjZjNkZGY5ZGRlNTdhZDgzYmZmNGZkNWMyYTlhZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u_H1ykkAftOPOX3aoTn3UuSFkDImlqj_5Fim4EwIX6E)

抱歉，这个问题我们先看看哈，会尽快修复

**Comment by moshangqi** [comment]
问题已修复，等 0.5.3 发布后即可正常
