### ISSUE TITLE
推荐用  postcss 替换 less 

### ISSUE THREAD

**Issue by DiamondYuan** [xudafeng/yuque-chrome-extension#37]
less 主要使用两个功能。 1. 变量， 2. 嵌套 。 

这两个功能都有原生方案了

https://caniuse.com/css-variables
https://caniuse.com/css-nesting

**Comment by vagusX** [comment]
当前会考虑继续使用现有的 Less 方案，保持既有的研发习惯，若 Less 缺点实在影响研发效率，再评估是否迁移到 PostCSS。

也许在下一个大版本或项目时，完全替换 Less 为 PostCSS 或其他方案。

**Comment by xudafeng** [comment]
感谢 @DiamondYuan 建议，后面会考虑的
