### ISSUE TITLE
使用剪藏把剪藏的内容保存到知识库的时候必须切换到全部文档才可以找到通过插件保存的文档

### ISSUE THREAD

**Issue by duoluodexiaoxiaoyuan** [xudafeng/yuque-chrome-extension#9]
我使用语雀默认新建的文档在目录下面是可以找到的，当我某个知识库下面有大量的文档，同时存在剪藏保存的文档，每次我检索必须通过切换到全部文档，才不会漏掉所有内容，这样似乎是不合理的。而且给人很混乱的感觉。

**Comment by xudafeng** [comment]
给剪藏来的文档一个专门的知识库会不会更好区分

**Comment by Stella9625** [comment]
似乎不会影响到检索文档，剪藏的文档默认出现在目录，且在最上面；可否截图或者录屏给我们看看你遇到的问题？

**Comment by duoluodexiaoxiaoyuan** [comment]
> 似乎不会影响到检索文档，剪藏的文档默认出现在目录，且在最上面；可否截图或者录屏给我们看看你遇到的问题？

检索确实可以，我说错了，但是看不到还是很难受，目前确实来个专门的知识库可以解决掉这个问题，但是就是无法和之前的内容完美的分类了，还需要自己再手动整理一次。还是期待直接做一次笔记就做好了，以后直接看就好了。
