### ISSUE TITLE
谷歌商城商店链接失效

### ISSUE THREAD

**Issue by xlu103** [xudafeng/yuque-chrome-extension#99]
![image](https://github.com/yuque/yuque-chrome-extension/assets/58740553/dea50128-3901-4138-8f8e-1ae49ac918f6)

这个谷歌链接失效。
链接为：https://chrome.google.com/webstore/detail/yuque-browser-extension-f/hnbdgfongnkfgnbpamndfiiedhapfecn

结果为：

![image](https://github.com/yuque/yuque-chrome-extension/assets/58740553/9e472c43-c313-4244-9b8b-89a53ccd34cd)

**Comment by moshangqi** [comment]
谷歌商店还在审核中，需要等 1-2 天恢复

**Comment by xudafeng** [comment]
还在审核中，快了

**Comment by xlu103** [comment]
收到
